version: 2

defaults: &defaults
  working_directory: /tmp/drafter
  docker:
    - image: circleci/ruby:2.4.1

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run: git submodule update --init --recursive
      - run: sudo apt-get install valgrind

      - run:
          name: Build
          environment:
            CXXFLAGS: '-Werror'
          command: |
            ./configure -i
            make drafter test-libdrafter test-capi

      - persist_to_workspace:
          root: bin
          paths:
            - bin/

  test:
    <<: *defaults
    parallelism: 4

    steps:
      - attach_workspace:
          at: /tmp/drafter/bin

      - run:
          name: Test libdrafter
          command: ./bin/test-libdrafter

      - run:
          name: Test C API
          command: ./bin/test-capi

      - run:
          name: Integration Tests
          command: bundle exec cucumber

      - run:
          name: Memory Test
          command: |
            mkdir artifacts
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --error-exitcode=1 ./bin/test-libdrafter 2> artifacts/memcheck.log
            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --error-exitcode=1 ./bin/test-capi 2> artifacts/memcheck-capi.log

      - store_artifacts:
          path: artifacts

  release:
    <<: *defaults

    branches:
      only:
        - /v.*/

    steps:
      - run: ./tools/release.sh

workflows:
  version: 2

  drafter:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
